import Head from 'next/head'
import Image from 'next/image'
import { InferGetServerSidePropsType } from 'next'

import Navbar from '@/components/Navbar/Navbar'

import styles from '@/styles/Home.module.css'
import robotStyles from '@/styles/Robots.module.css'

import { RobotData } from '@/@shared-types/RobotData'
import Robot from '@/components/Robots/Robot/Robot'

export async function getServerSideProps() {

    // Fetch data from external API
    const res = await fetch(`https://www.team5599.com/api/robots`)
    const data : {message : string, payload : RobotData[] } = await res.json()
  
    return {
        props: { data }, // will be passed to the page component as props
    }

}

export default function Robots( { data } : InferGetServerSidePropsType<typeof getServerSideProps>) {

    console.log("data", data);

    return (
        <>
            <Head>
                <title>The Sentinels - FRC Team 5599</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <main className={styles.main}>
                <div className={robotStyles['robot-grid']}>
                    {
                        data.payload.map((robotItem, index) => {
                            return <Robot key={robotItem._id} robotData={robotItem}/>
                        })
                    }
                </div>
            </main>
        </>
    )
}