name: CI

on:
  push:
    branches:
      - main
      - heroku

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run ESLint
        run: npm run lint
  deploy:
    needs: eslint
    if: github.ref == 'refs/heads/heroku' && needs.eslint.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13 # External action to push to the heroku repository
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bnchs-robotics-website-v5"
          heroku_email: "sentinels.pro@gmail.com"